version: '3.3'

services:

#  traefik:
#    image: traefik:v2.0
#    container_name: traefik
#    restart: unless-stopped
#    security_opt:
#      - no-new-privileges:true
#    command:
##      - "--log.level=DEBUG"
#      - "--api.insecure=true"
#      - "--providers.docker=true"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.web.address=:80"
#      - "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
#      - "--certificatesresolvers.mytlschallenge.acme.email=myname@mydomain.eus"
#      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"

#    ports:
#      - "80:80"
#      - "443:443"
#      - "8080:8080"
#    volumes:
#      - /etc/localtime:/etc/localtime:ro
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
#      - ./letsencrypt:/letsencrypt

  web:
    build: .
    container_name: elkarforti
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true 
    volumes:
      #- ./elkarforti:/data/web
      - ./keys:/etc/elkarforti
      - ./db:/db
      - /etc/localtime:/etc/localtime:ro
    env_file: env
    ports:
      - "8000:8000"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.web_router_https.rule=Host(`${ALLOWED_HOSTS}`)"
#      - "traefik.http.routers.web_router_https.entrypoints=web"
#      - "traefik.http.routers.web_router_https.entrypoints=websecure"
#      - "traefik.http.routers.web_router_https.tls.certresolver=mytlschallenge"
#      # Enable http --> https redirect
#      - "traefik.http.routers.web_router_http.rule=Host(`${ALLOWED_HOSTS}`)"
#      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.web_router_http.middlewares=https_redirect"
