# Generated by Django 2.2.7 on 2019-11-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortiParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fortiIP', models.CharField(max_length=16)),
                ('fortiPort', models.IntegerField(default=443)),
                ('fortiVdom', models.CharField(max_length=32)),
                ('fortiUserName', models.CharField(max_length=32)),
                ('fortiPassword', models.CharField(max_length=128)),
                ('fortiDefaultGroupName', models.CharField(max_length=32)),
                ('fortiAccessEnabledGroupName', models.CharField(max_length=32)),
            ],
        ),
    ]
