# Generated by Django 2.2.7 on 2019-11-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0007_auto_20191117_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortiparameters',
            name='fortiCipheredData',
            field=models.CharField(default=' ', max_length=128),
        ),
        migrations.AlterField(
            model_name='fortiparameters',
            name='fortiCipheredIV',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
