# Generated by Django 2.2.7 on 2019-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0009_auto_20191117_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortiparameters',
            name='fortiCipheredIV',
            field=models.CharField(default='-', max_length=16),
        ),
    ]
