# Generated by Django 2.2.7 on 2019-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0011_auto_20191118_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fortiparameters',
            name='fortiCipheredIV',
            field=models.CharField(default='-', max_length=128),
        ),
    ]
