# Generated by Django 2.2.7 on 2019-11-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0012_auto_20191118_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortiparameters',
            name='fortiCipheredData',
        ),
        migrations.RemoveField(
            model_name='fortiparameters',
            name='fortiCipheredIV',
        ),
    ]
