# Generated by Django 2.2.7 on 2020-01-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0013_auto_20191118_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortiparameters',
            name='fortiKeyStorePath',
            field=models.CharField(default='/etc/elkarforti/', max_length=128),
        ),
    ]
