# Generated by Django 3.0.2 on 2020-02-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupaccess', '0015_auto_20200120_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fortiparameters',
            name='automaticCloseTime',
        ),
        migrations.RemoveField(
            model_name='fortiparameters',
            name='automaticOpenClose',
        ),
        migrations.RemoveField(
            model_name='fortiparameters',
            name='automaticOpenTime',
        ),
    ]
